testdriverai/cli

lib/analytics.js, lib/config.js, lib/notify.js, lib/speak.js, package.json
Parses appropriate env values
provides defaults for env values
=> Added a config.js file

index.js, lib/config.js, lib/sdk.js, package.json
Added TD_API_ROOT Option
Added TD_DEV option
=> Added Config Options and --help

.gitignore, package-lock.json
Added package-lock.json
This file should be committed to the repo since it pins the versions of
packages. Should be updated at least every time package.json is updated,
perhaps more
=> Removed package-lock.json from .gitignore

lib/commander.js, lib/commands.js, lib/config.js
There's a supporting [PR](https://github.com/replayableio/api/pull/190) for this in the api repo. 
I had to rename the variable to choose the search algorithm, just for `scroll-until-text/image` , feel free to change the variable name if you find anything better.
=> Add scroll using mouse option

lib/commander.js, lib/commands.js
Add an optional delay param to the "type" command
=> Update the type command to accept an optional delay parameter

lib/redraw.js
Still a problematic function- takes too long to take screenshot
But this fixes it as is
=> Fixed Redraw

agent.js, package.json
Now all vars are contained in a JSON object called TD_INTERPOLATION_VARS
=> Interpolation Vars Change

agent.js
This allows for markdown instructions to contain censored vars
=> Added Interpolation to prompt

lib/commands.js
=> delay is actually cpm

lib/init.js
https://www.notion.so/Still-writes-after-SIGINT-1f46adb97c8880c6b1d7f9cb54c33322?pvs=4
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #214 
- <kbd>&nbsp;1&nbsp;</kbd> #213 👈
=> TD-1742 – Properly exit on SIGINT during prompts

.github/workflows/publish-acceptance-tests.yml
Attempting to resolve https://github.com/testdriverai/testdriverai/actions/runs/15350859755/job/43198468482
=> Require beta to be published first

package.json
> https://mintlify.com/docs/quickstart#code-based-workflow
=> Add "docs" npm script for running Mintlify docs locally

docs/overview/quickstart.mdx
https://www.notion.so/Make-Step-1-of-Quick-Start-Create-a-TestDriver-Account-20d6adb97c8881ea8d6cf001dabbd352?source=copy_link
https://dashboard.mintlify.com/testdriver/testdriver/editor/TD-2078
> [!NOTE]
> Mintlify's editor doesn't seem to correctly render the hyperlink Card as seen here:
> https://mintlify.com/docs/components/cards
> The props seem correct and _should_ work.
> <img width="672" alt="Screenshot 2025-06-09 at 3 06 44 PM" src="https://github.com/user-attachments/assets/36867815-2f58-4e2a-9d19-2fb6993ebb92" />
=> TD-2078 – Step 1 – Create a Test Driver Account

docs/commands/scroll-until-text.mdx
What's the rush? Sometimes ya just gotta "scroll with it."
TD-2083
=> add note to docs about "scroll" and "keyboard" methods

agent.js, testdriver/edge-cases/prompt-in-middle.yaml, testdriver/edge-cases/prompt-nested.yaml
=> handle embedded prompts with no commands

lib/commands.js
Expected:
> Search Phrase
Actual:
> earch Phrase
=> Wait 1s before typing into search field

lib/parser.js
Reverts testdriverai/testdriverai#285
=> Revert "TD-2151 – throw if an env variable is missing"

testdriver/scroll.yaml
https://www.notion.so/Add-acceptance-tests-for-scroll-21c6adb97c8881c2ba22d4a99d953afe?source=copy_link
=> TD-2191 – Acceptance test for scrolling with the mouse

CONTRIBUTING.md
https://www.notion.so/v5-Technical-Audit-21b6adb97c8880dbb2bbc47aafb59872?source=copy_link
=> Add Architecture & Network Diagrams

agent.js, docs/cli/overview.mdx
I use this when I'm running tests locally and the website is already in view.
=> add ability to skip prerun with flag

lib/commands.js, testdriver/acceptance/exec-js.yaml, testdriver/acceptance/exec-shell.yaml
=> TD-2229 - Fix for Windows Output

testdriver/acceptance/drag-and-drop.yaml
This gets straight to drag-and-drop instead of several setup steps.
This won't pass until https://github.com/testdriverai/api/pull/14 lands
Hell yes!
https://app.testdriver.ai/replay/687abb7003675a6aef110733?share=in74a7NCERrIRNSwCKxInA
=> TDT-102 – Refactor drag-and-drop

agent/index.js
If connectToSandboxDirect fails due to 404, default to new image.
This may not entirely 
fix 
https://www.notion.so/The-instance-ID-i-does-not-exist-2396adb97c8880bba541de134baf01cf?source=copy_link,
but it will at least improve some of the logging to know what’s going 
on.
=> Fallback to createNewSandbox

agent/events.js, agent/index.js, agent/lib/sandbox.js
We should be able to measure client UX in datadog after this.
=> add analytics to websocket events

docs/action/ami.mdx
=> TDT-137 – Customization must happen as testdriver user

agent/lib/parser.js, schema.json
- Migrate to [latest draft](https://json-schema.org/draft/2020-12)
- Removed performance redundancies like `contains`
- Should work for all the cases now 🤞
I also **tried** to vibe code a simple site to validate our data using this schema, seems pretty accurate
_This is what AI should be used for_
but again its vibe coded, so take it with a grain of salt - https://v0-json-validator-site.vercel.app/
If you want to play around, I have also put this [other branch](https://github.com/testdriverai/cli/tree/tarun/schema-playground) and u can play by modifying the [data.yaml](https://github.com/testdriverai/cli/blob/tarun/schema-playground/data.yaml) file and then running [test.py](https://github.com/testdriverai/cli/blob/tarun/schema-playground/test.py) (install json, yaml and jsonschema py …
=> Fix json-schema

agent/lib/parser.js, schema.json
=> Revert "Fix json-schema"

docs/commands/hover-text.mdx, docs/commands/wait-for-text.mdx, schema.json, testdriver/acceptance/hover-text-with-single-characters.yaml
**New tests may not pass without https://github.com/replayableio/haxor-uied/pull/3**
=> TDT-139 – Add hover-text-with-single-characters test

testdriver/acceptance/remember.yaml
Ran it locally and works like a charm - https://app.dashcam.io/replay/689a1c9dd00671871093c669?share=NLvS40Gq76fe9jQ8IKk2Q
=> add test for remember [skip ci]

docs/getting-started/playwright.mdx
- change the before code to normal playwright code
- change the default npm install for playwright to make it a one-liner, _less work on the user side_
=> Fix playwright docs

docs/apps/tauri-apps.mdx, docs/docs.json, docs/styles.css
https://www.notion.so/Tauri-TestDriver-Docs-2796adb97c8880b98d77d70b53c1a7e3?v=1f46adb97c88807ca025000c05b7b897&source=copy_link
=> docs: Tauri Apps
