testdriverai/cli

lib/focus-application.js, package.json
So when I ran v.35 on Wrap I used to get this error 
```
osascript -e 'tell application "Warp" to set miniaturized of every window to true'
27:67: execution error: Warp got an error: Can’t set miniaturized of every window to true. (-10006)
```
And also when the command / action is performed the terminal wasn't reopening, so most of the times it was a guessing game whether to switch the win or wait assuming its thinking lol.
So this fixes it, but it still has a couple of things to note.
- Does not minimize if the terminal is in full screen BUT will bring it back on once the action is performed. 
- In windows, as of now, it minimizes but doesn't reopen the terminal, will try to make a commit for that. (Edit : it's working rn on .39, but still getting the same issue on mac)
Also make sure to …
=> Feat: Fix exec terminal not reopening after execution in mac

lib/focus-application.js, package.json
So the issue with having a same function is maximizing or activating the terminal doesn't work when the command is executing something in a full screen window.
Made a loom rec explainig / demonstrating as to why - here's the [link](https://www.loom.com/share/462adfb66c2145c1999877c08e370db9?sid=681fc0f5-4085-4f21-8e58-413fa88a7d28)
=> min and max scripts for mac needs to be different.

agent.js
The `/generate` command creates filenames that contains special chars. 
These chars makes the [quickstart-web](https://github.com/testdriverai/quickstart-web) (the generate test form thing) unable to create `pr-branch` 
Could have been fixed in the quickstart-web to stripe out the special chars before creating the pr-branches but felt this is more robust. 
[Here's](https://github.com/testdriverbot/allthingswiki-1735897614210/actions/runs/12595816911/job/35105909481) an ex of the problem this thing created
=> Fix: Generate func creating filenames

lib/commands.js
Robotjs will miss repeated character if there is no delay, so we added a global delay.
However this slows down typing globally.
This PR only slows typing conditionally.
=> typing repeated chars

lib/commander.js, lib/commands.js, lib/outputs.js
Adds:
- `exec` command with properties:
- `cli` the cli command to run
- `output` the name of the output variable
Here is example usage
```yml
version: 4.2.10
session: 67a3fdacd06c99b9c179b566
steps:
- prompt: exec
commands:
- command: exec
cli: pwd
silent: false
output: my_var
- prompt: type ls
commands:
- command: type
text: ${OUTPUT.my_var}
```
And example output
```sh
❯ node index.js run testdriver/testdriver.yml
Spawning GUI...
Howdy! I'm TestDriver v4.2.13
Working on /Users/ianjennings/Development/testdriverai/testdriver/testdriver.yml
This is beta software!
Join our Discord for help
https://discord.com/invite/cWDFW8DzPm
running /Users/ianjennings/Development/testdriverai/testdriver/testdriver.yml...
exec
command='exec' cli='pwd' output='my_var' …
```
=> Add exec command

.github/workflows/format.yml, package-lock.json
- Updated `package-lock.json` to support `npm ci` with a frozen lockfile.
- Replaced `npm install` with `npm ci` for faster and more reliable CI installs.
- Fixed Prettier command to check formatting instead of formatting files.
- Configured CI to error on warnings for stricter code quality enforcement.
=> chore: Improve CI checks for eslint + prettier

lib/notify.js, lib/speak.js
```shell
/Users/eric/Projects/testdriverai/testdriverai/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifie
r -title "TestDriver.ai" -message "command='type' text='hi'" -timeout "5" -appIcon "/Users/eric/Projects/testdriverai/testdriverai/lib/images/icon.png" -json "true"
zsh: bad CPU type in executable: /Users/eric/Projects/testdriverai/testdriverai/node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
```
=> Silently handle node-notifier errors

.github/workflows/publish-acceptance-tests.yml
- Updated GitHub Actions workflow to publish pre-release versions under the "canary" tag instead of "beta"  
- Renamed the publish job accordingly and changed the npm publish tag to "canary"  
- Set unique prerelease versions including the commit hash for better traceability  
- Adjusted test jobs to depend on the new canary publish job and use the canary version for testing  
- Updated package.json version to reflect the canary pre-release state  
- Improved release management by clearly distinguishing unstable builds from beta releases
=> ci: switch publish workflow from beta to canary tag

.github/workflows/publish-acceptance-tests.yml
See:
https://github.com/orgs/community/discussions/103114#discussioncomment-8359045
If this works, then I can add a branch protection rule to https://github.com/testdriverai/testdriverai/settings/branch_protection_rules/54177906 that requires this check:
> ![Screenshot 2025-06-02 at 12 50 33 PM](https://github.com/user-attachments/assets/17e304b8-cfd4-477e-b640-ecac3b5a5dfc)
That *should* force it to run in the Merge Queue.
=> Add Acecptance Tests to pull_requests, but skip them

.github/workflows/publish-acceptance-tests.yml, .github/workflows/publish-latest.yml
**EDIT**
This **removes** GitHub's buggy Merge Queue. (It was running, but not reporting statuses back!)
Instead, this basically moves the logic onto `main`:
1. Run "Acceptance Tests" on push to `main`
2. If they pass, publish `@latest`.
=> Remove Merge Queue

lib/commands.js
This PR fixes right and left scroll functionality.
Idk how to explain this, other than some testing during the birth would have been nice. 
Had an usecase where I needed to scroll right, it didn't work, saw the [robotjs](https://github.com/octalmage/robotjs) repo, couldn't really understand / point out to the implementation.
So wrote a simple script 
```js
const robot = require("robotjs");
console.log("Waiting 5 seconds before scrolling...");
setTimeout(() => {
robot.scrollMouse(300, 0);
console.log("Horizontal scroll completed!");
}, 5000);
```
And experimented, `scrollMouse` params are `(x, y)` direction, `300` means usually, generally, we understand as scroll right right ? guess what, surprise surprise, its actually `-300`.  
`300` will scroll to left, which most of the times nothing …
=> fix right and left scroll

docs/guide/lifecycle-prerun.mdx
The `lifecycle/prerun.yaml` script is run always, no matter the environment.
The `prerun` value from GitHub actions is only run via GitHub actions and only affects Windows machines.
=> Remove incorrect mermaid chart from prerun docs

.prettierignore, docs/commands/scroll-until-image.mdx, lib/commander.js, lib/commands.js, schema.json
> https://www.notion.so/scroll-until-image-should-also-accept-a-path-to-use-match-image-2166adb97c888122aaf0ecc97fbe572c?source=copy_link
- - Added support for using either `description` or `path` as the image identifier in the `scroll-until-image` command.
- Updated the schema to require either `path` or `description`, enhancing flexibility and accuracy.
- Modified `scroll-until-image` to pass `object.path`.
- Implemented assertion for `description` and matching logic for `path` in image matching.
- Updated `match-image` to return `throw` or `true`.
- Improved documentation with known issues and detailed scrolling workarounds, including keyboard-based scrolling.
- Added `schema.json` to `.prettierignore`
=> TD-2165 – Add `path` support for `scroll-until-image`

lib/commands.js
This fixes issues of unable to press shortcuts that involves multiple [modifier keys](https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.modifierkeys?view=windowsdesktop-9.0)
So the fix was basically replacing robotjs `keyToggle` with `keyTap` and passing in the modifier keys as the array (second argument) as there's some weird issue at robotjs end, like we cannot do this 
```js
robot.keyToggle(command, "down");
robot.keyToggle(alt, "down");
robot.keyTap(i)
robot.keyToggle(command, "up");
robot.keyToggle(alt, "up");
```
but instead need to do this ` robot.keyTap('i', ['command', 'alt']);` 
I am also unsure as to why it wasn't done this way initially, but I am guessing some other issue at their end prevented it. 
anyways, …
=> TD-2179: fix mutliple modifier keys (local)

agent.js
Fix is simple, `thisFile` has the initial file path or basically the second argument https://github.com/testdriverai/testdriverai/blob/3f5f3f84eb9496120ea1891405aac2748de46d62/agent.js#L1245
Hence we update it only if the `file` is provided, i.e, again the second argument during `/run` 
[here's](https://www.loom.com/share/10db36c2181f4197b31cc828b8d739b7?sid=1ec2a8c1-c8cc-4040-9582-73d48d8d6898) the loom of its working
=> TD-2201 fix /run without file path

agent/index.js, agent/interface.js, interfaces/cli/lib/base.js, testdriver/behavior/lifecycle/postrun.yaml, testdriver/behavior/lifecycle/prerun.yaml, testdriver/behavior/lifecycle/provision.yaml
https://www.notion.so/postrun-lifecycle-script-doesn-t-run-test-failure-23a6adb97c888026a58bc62804a1bc1b?v=1f46adb97c88807ca025000c05b7b897&source=copy_link
I spent a while doing this by hand, but there were so many places that `runLifeCycle` was called (or an `await ...` wasn't being caught) that I had Cursor just wrap everything until we found the right place in code [a6b4110](https://github.com/testdriverai/cli/pull/368/commits/a6b41100e781c911abe95cd373c8affda8f0941c) and then removed the noise [f7af058](https://github.com/testdriverai/cli/pull/368/commits/f7af058c3d1348039ab2949b6b142b61ab0df2c6).
As you can see in the demos, `prerun.yaml` executes, **but wasn't running `postrun.yaml`**.
With this change, it always runs with `run`, but _not_ with `edit`.
```console
$ npm run dev run …
```
=> TDT-129 – Always run postrun, even on failure

agent/events.js, agent/index.js, agent/lib/debugger-server.js, agent/lib/debugger.js, agent/lib/system.js, testdriver/acceptance/assert.yaml
This fixes issues when running multiple instances within the same process. We don't want those instances to share emitters.
=> single emitter per instance

.github/workflows/acceptance-v6.yml, docs/features/parallel-testing.mdx
- Limited acceptance tests to 8 to avoid hitting API "Max instances" limits.
- Added documentation for the max-parallel setting to control concurrency in GitHub Actions workflows.
https://www.notion.so/Document-Concurrency-2386adb97c888033bcabdd4e9169864c?source=copy_link
=> TDT-124 – Document `max-parallels` (and limit our CI usage)

agent/index.js
In scripts, there may be variables that TestDriver isn’t aware of 
because the environment is different
```console
Howdy! I'm TestDriver v6.0.10
Starting debugger server...
This is beta software!
Join our Forums for help
https://forums.testdriver.ai
Working on /Users/eric/Projects/testdriverai/cli/testdriver/acceptance/hover-text-with-single-characters.yaml
- establishing connection...
Unreplaced variables in YAML: DOES_NOT_EXIST
- authenticating...
```
=> TDT-140 – log.warn for replaced variables

agent/index.js, agent/lib/commands.js, agent/lib/redraw.js
It seems like `redraw` might be spawaning new intervals for every command, at least within VS Code. I can see in datadog that a single machine is sending 3 network commands per second, yet the interval is `15000ms`.
=> dont scope sub functions

agent/lib/redraw.js
Printing unnecessary log in the prod l[ike this](https://github.com/testdriverai/pieces/actions/runs/16676428898/job/47204056398#step:3:27)
so after the PR it only gets logged while doing `npm run dev` 
_PS: stopping the acceptance tests for this, to save time and resources 🤌_
=> rm unwanted logging

.github/workflows/acceptance-tests.yml
This wasn’t running on `main` because the `if` statement only targetted 
pull_request_review.
=> Support other events

agent/lib/sdk.js
After authentication, share token globally.
Otherwise, each `createSdk` references a different token.
=> There can only be 1 single token

agent/index.js, interfaces/cli/lib/base.js, testdriver/behavior/lifecycle/postrun.yaml, testdriver/behavior/lifecycle/prerun.yaml, testdriver/behavior/lifecycle/provision.yaml
This logic prevents postrun from running in a loop if it encounters an error. It can be tested with:
```
node bin/testdriverai.js run testdriver/behavior/failure.yaml
```
=> Prevent postrun from infinite loop

agent/index.js, interfaces/readline.js
if the prompt was : `> /explore go to youtube.com` 
it would interpret the "go to youtube.com" as args so they would become ["go", "to", "youtube.com"]
anyways, it was pretty simple fix, mainly due to the fact that every prompt is ran in [exploratory mode](https://github.com/testdriverai/cli/blob/79cbdf520030fee9d05b34b41ecf448e03b48aeb/interfaces/readline.js#L149-L157) other than /run and other meta commands.
Also removed some unnecessary logging, I just commented them out, happy to just remove it as well
_I guess it was added for debugging sake and wasn't removed later._
=> fix handling for /explore in the prompt

agent/index.js, agent/interface.js
This solves the issue where connection failures are not rendered in `junit.xml`. This is example output when the server isn not running at all.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" errors="0" skipped="0">
<testsuite name="testdriver/edge-cases" tests="1" failures="1" errors="0" skipped="0">
<testcase classname="testdriver/edge-cases" name="js-promise.yaml" time="0.858">
<failure message="Failed commands: exec"/>
<system-out><![CDATA[Starting ****ger server...
This is beta software!
Join our Discord for help
https://discord.com/invite/cWDFW8DzPm
exiting...
running /Users/ianjennings/Development/cli/testdriver/edge-cases/lifecycle/postrun.yaml...
> postrun cleanup
postrun.yaml:4:6 (exec)
exec
command='exec' code='console.log("POSTRUN EXECUTED …
```
=> Emit "test.start" before connection happens

agent/index.js, agent/interface.js
Prompt Input for `generate` command
```
❯ node bin/testdriverai.js generate --help                                              
Generate test files based on current screen state
USAGE
$ testdriverai generate [PROMPT] [FILE] [--count <value>] [--headless] [--new] [--sandbox-ami <value>] [--sandbox-instance <value>]
ARGUMENTS
PROMPT  Multi-line text prompt describing what to generate
FILE    Base test file to run before generating (optional)
FLAGS
--count=<value>             [default: 3] Number of test files to generate
--headless                  Run in headless mode (no GUI)
--new                       Create a new sandbox instead of reconnecting to an existing one
--sandbox-ami=<value>       Specify AMI ID for sandbox instance (e.g., ami-1234)
--sandbox-instance=<value>  Specify EC2 …
```
=> Add "prompt" command to generate
